# Generated by Django 3.2.4 on 2021-06-28 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_veiculo_ano'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['-data_compra']},
        ),
        migrations.AddField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Vendido', 'Vendido')], default='Disponivel', max_length=12),
        ),
        migrations.AddField(
            model_name='venda',
            name='carro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.veiculo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
