# Generated by Django 3.2.4 on 2021-06-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210628_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['-data_compra']},
        ),
        migrations.AddField(
            model_name='venda',
            name='comprador',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
