# Generated by Django 3.2.4 on 2021-06-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210628_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='data_compra',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
