# Generated by Django 3.2.4 on 2021-06-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_veiculo_data_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Vendido', 'Vendido')], default='Disponivel', max_length=12),
        ),
    ]
