# Generated by Django 3.2.4 on 2021-06-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_venda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Vendido', 'Vendido')], default='Vendido', max_length=12),
        ),
    ]
