# Generated by Django 3.2.4 on 2021-06-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_venda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('Disponivel', 'Disponivel'), ('Vender', 'Vender')], default='Vendido', max_length=12),
        ),
    ]
