# Generated by Django 3.2.4 on 2021-06-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_venda_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['-data_venda']},
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='data_compra',
            new_name='data_venda',
        ),
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('Disponivel', 'Disponivel'), ('Vender', 'Vender')], default='Vender', max_length=12),
        ),
    ]
