# Generated by Django 3.2.4 on 2021-06-29 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210629_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='carro',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.veiculo'),
        ),
    ]
